-- Andaman & Nicobar
INSERT INTO Cities (name,state_id)
VALUES('Alipur', '1'),
('Andaman Island', '1'),
('Anderson Island', '1'),
('Arainj-Laka-Punga', '1'),
('Austinabad', '1'),
('Bamboo Flat', '1'),
('Barren Island', '1'),
('Beadonabad', '1'),
('Betapur', '1'),
('Bindraban', '1'),
('Bonington', '1'),
('Brookesabad', '1'),
('Cadell Point', '1'),
('Calicut', '1'),
('Chetamale', '1'),
('Cinque Islands', '1'),
('Defence Island', '1'),
('Digilpur', '1'),
('Dolyganj', '1'),
('Flat Island', '1'),
('Geinyale', '1'),
('Great Coco Island', '1'),
('Haddo', '1'),
('Havelock Island', '1'),
('Henry Lawrence Island', '1'),
('Herbertabad', '1'),
('Hobdaypur', '1'),
('Ilichar', '1'),
('Ingoie', '1'),
('Inteview Island', '1'),
('Jangli Ghat', '1'),
('Jhon Lawrence Island', '1'),
('Karen', '1'),
('Kartara', '1'),
('KYD Islannd', '1'),
('Landfall Island', '1'),
('Little Andmand', '1'),
('Little Coco Island', '1'),
('Long Island', '1'),
('Maimyo', '1'),
('Malappuram', '1'),
('Manglutan', '1'),
('Manpur', '1'),
('Mitha Khari', '1'),
('Neill Island', '1'),
('Nicobar Island', '1'),
('North Brother Island', '1'),
('North Passage Island', '1'),
('North Sentinel Island', '1'),
('Nothen Reef Island', '1'),
('Outram Island', '1'),
('Pahlagaon', '1'),
('Palalankwe', '1'),
('Passage Island', '1'),
('Phaiapong', '1'),
('Phoenix Island', '1'),
('Port Blair', '1'),
('Preparis Island', '1'),
('Protheroepur', '1'),
('Rangachang', '1'),
('Rongat', '1'),
('Rutland Island', '1'),
('Sabari', '1'),
('Saddle Peak', '1'),
('Shadipur', '1'),
('Smith Island', '1'),
('Sound Island', '1'),
('South Sentinel Island', '1'),
('Spike Island', '1'),
('Tarmugli Island', '1'),
('Taylerabad', '1'),
('Titaije', '1'),
('Toibalawe', '1'),
('Tusonabad', '1'),
('West Island', '1'),
('Wimberleyganj', '1'),
('Yadita', '1');

-- Andhra Pradesh
INSERT INTO Cities (name,state_id)
VALUES('Adilabad', '2'),
('Anantapur', '2'),
('Chittoor', '2'),
('Cuddapah', '2'),
('East Godavari', '2'),
('Guntur', '2'),
('Hyderabad', '2'),
('Karimnagar', '2'),
('Khammam', '2'),
('Krishna', '2'),
('Kurnool', '2'),
('Mahabubnagar', '2'),
('Medak', '2'),
('Nalgonda', '2'),
('Nellore', '2'),
('Nizamabad', '2'),
('Prakasam', '2'),
('Rangareddy', '2'),
('Srikakulam', '2'),
('Visakhapatnam', '2'),
('Vizianagaram', '2'),
('Warangal', '2'),
('West Godavari', '2');

-- Arunachal Pradesh
INSERT INTO Cities (name,state_id)
VALUES('Anjaw', '3'),
('Changlang', '3'),
('Dibang Valley', '3'),
('East Kameng', '3'),
('East Siang', '3'),
('Itanagar', '3'),
('Kurung Kumey', '3'),
('Lohit', '3'),
('Lower Dibang Valley', '3'),
('Lower Subansiri', '3'),
('Papum Pare', '3'),
('Tawang', '3'),
('Tirap', '3'),
('Upper Siang', '3'),
('Upper Subansiri', '3'),
('West Kameng', '3'),
('West Siang', '3');

-- Assam
INSERT INTO Cities (name,state_id)
VALUES('Barpeta', '4'),
('Bongaigaon', '4'),
('Cachar', '4'),
('Darrang', '4'),
('Dhemaji', '4'),
('Dhubri', '4'),
('Dibrugarh', '4'),
('Goalpara', '4'),
('Golaghat', '4'),
('Guwahati', '4'),
('Hailakandi', '4'),
('Jorhat', '4'),
('Kamrup', '4'),
('Karbi Anglong', '4'),
('Karimganj', '4'),
('Kokrajhar', '4'),
('Lakhimpur', '4'),
('Marigaon', '4'),
('Nagaon', '4'),
('Nalbari', '4'),
('North Cachar Hills', '4'),
('Silchar', '4'),
('Sivasagar', '4'),
('Sonitpur', '4'),
('Tinsukia', '4'),
('Udalguri', '4');

-- Bihar
INSERT INTO Cities (name,state_id)
VALUES('Araria', '5'),
('Aurangabad', '5'),
('Banka', '5'),
('Begusarai', '5'),
('Bhagalpur', '5'),
('Bhojpur', '5'),
('Buxar', '5'),
('Darbhanga', '5'),
('East Champaran', '5'),
('Gaya', '5'),
('Gopalganj', '5'),
('Jamshedpur', '5'),
('Jamui', '5'),
('Jehanabad', '5'),
('Kaimur (Bhabua)', '5'),
('Katihar', '5'),
('Khagaria', '5'),
('Kishanganj', '5'),
('Lakhisarai', '5'),
('Madhepura', '5'),
('Madhubani', '5'),
('Munger', '5'),
('Muzaffarpur', '5'),
('Nalanda', '5'),
('Nawada', '5'),
('Patna', '5'),
('Purnia', '5'),
('Rohtas', '5'),
('Saharsa', '5'),
('Samastipur', '5'),
('Saran', '5'),
('Sheikhpura', '5'),
('Sheohar', '5'),
('Sitamarhi', '5'),
('Siwan', '5'),
('Supaul', '5'),
('Vaishali', '5'),
('West Champaran', '5');

-- Chandigarh
INSERT INTO Cities (name,state_id)
VALUES('Chandigarh', '6'),
('Mani Marja', '6');

-- Chhattisgarh
INSERT INTO Cities (name,state_id)
VALUES('Bastar', '7'),
('Bhilai', '7'),
('Bijapur', '7'),
('Bilaspur', '7'),
('Dhamtari', '7'),
('Durg', '7'),
('Janjgir-Champa', '7'),
('Jashpur', '7'),
('Kabirdham-Kawardha', '7'),
('Korba', '7'),
('Korea', '7'),
('Mahasamund', '7'),
('Narayanpur', '7'),
('Norh Bastar-Kanker', '7'),
('Raigarh', '7'),
('Raipur', '7'),
('Rajnandgaon', '7'),
('South Bastar-Dantewada', '7'),
('Surguja', '7');

-- Dadra & Nagar Haveli
INSERT INTO Cities (name,state_id)
VALUES('Amal', '8'),
('Amli', '8'),
('Bedpa', '8'),
('Chikhli', '8'),
('Dadra & Nagar Haveli', '8'),
('Dahikhed', '8'),
('Dolara', '8'),
('Galonda', '8'),
('Kanadi', '8'),
('Karchond', '8'),
('Khadoli', '8'),
('Kharadpada', '8'),
('Kherabari', '8'),
('Kherdi', '8'),
('Kothar', '8'),
('Luari', '8'),
('Mashat', '8'),
('Rakholi', '8'),
('Rudana', '8'),
('Saili', '8'),
('Sili', '8'),
('Silvassa', '8'),
('Sindavni', '8'),
('Udva', '8'),
('Umbarkoi', '8'),
('Vansda', '8'),
('Vasona', '8'),
('Velugam', '8');

-- Daman and Diu
INSERT INTO Cities (name,state_id)
VALUES('Brancavare', '9'),
('Dagasi', '9'),
('Daman', '9'),
('Diu', '9'),
('Magarvara', '9'),
('Nagwa', '9'),
('Pariali', '9'),
('Passo Covo', '9');

-- Delhi
INSERT INTO Cities (name,state_id)
VALUES('Central Delhi','10'),
('East Delhi','10'),
('New Delhi','10'),
('North Delhi','10'),
('North East Delhi','10'),
('North West Delhi','10'),
('Old Delhi','10'),
('South Delhi','10'),
('South West Delhi','10'),
('West Delhi','10');

--  Goa
INSERT INTO Cities (name,state_id)
VALUES('Canacona','11'),
('Candolim','11'),
('Chinchinim','11'),
('Cortalim','11'),
('Goa','11'),
('Jua','11'),
('Madgaon','11'),
('Mahem','11'),
('Mapuca','11'),
('Marmagao','11'),
('Panji','11'),
('Ponda','11'),
('Sanvordem','11'),
('Terekhol','11');

-- Gujarat
INSERT INTO Cities (name,state_id)
VALUES('Ahmedabad','12'),
('Amreli','12'),
('Anand','12'),
('Banaskantha','12'),
('Baroda','12'),
('Bharuch','12'),
('Bhavnagar','12'),
('Dahod','12'),
('Dang','12'),
('Dwarka','12'),
('Gandhinagar','12'),
('Jamnagar','12'),
('Junagadh','12'),
('Kheda','12'),
('Kutch','12'),
('Mehsana','12'),
('Nadiad','12'),
('Narmada','12'),
('Navsari','12'),
('Panchmahals','12'),
('Patan','12'),
('Porbandar','12'),
('Rajkot','12'),
('Sabarkantha','12'),
('Surat','12'),
('Surendranagar','12'),
('Vadodara','12'),
('Valsad','12'),
('Vapi','12');

-- Haryana
INSERT INTO Cities (name,state_id)
VALUES('Ambala','13'),
('Bhiwani','13'),
('Faridabad','13'),
('Fatehabad','13'),
('Gurgaon','13'),
('Hisar','13'),
('Jhajjar','13'),
('Jind','13'),
('Kaithal','13'),
('Karnal','13'),
('Kurukshetra','13'),
('Mahendragarh','13'),
('Mewat','13'),
('Panchkula','13'),
('Panipat','13'),
('Rewari','13'),
('Rohtak','13'),
('Sirsa','13'),
('Sonipat','13'),
('Yamunanagar','13');

-- Himachal Pradesh
INSERT INTO Cities (name,state_id)
VALUES('Bilaspur','14'),
('Chamba','14'),
('Dalhousie','14'),
('Hamirpur','14'),
('Kangra','14'),
('Kinnaur','14'),
('Kullu','14'),
('Lahaul & Spiti','14'),
('Mandi','14'),
('Shimla','14'),
('Sirmaur','14'),
('Solan','14'),
('Una','14');

-- Jammu & Kashmir
INSERT INTO Cities (name,state_id)
VALUES('Anantnag','15'),
('Baramulla','15'),
('Budgam','15'),
('Doda','15'),
('Jammu','15'),
('Kargil','15'),
('Kathua','15'),
('Kupwara','15'),
('Leh','15'),
('Poonch','15'),
('Pulwama','15'),
('Rajauri','15'),
('Srinagar','15'),
('Udhampur','15');

-- Jharkhand
INSERT INTO Cities (name,state_id)
VALUES('Bokaro','16'),
('Chatra','16'),
('Deoghar','16'),
('Dhanbad','16'),
('Dumka','16'),
('East Singhbhum','16'),
('Garhwa','16'),
('Giridih','16'),
('Godda','16'),
('Gumla','16'),
('Hazaribag','16'),
('Jamtara','16'),
('Koderma','16'),
('Latehar','16'),
('Lohardaga','16'),
('Pakur','16'),
('Palamu','16'),
('Ranchi','16'),
('Sahibganj','16'),
('Seraikela','16'),
('Simdega','16'),
('West Singhbhum','16');

-- Karnataka
INSERT INTO Cities (name,state_id)
VALUES('Bagalkot','17'),
('Bangalore','17'),
('Bangalore Rural','17'),
('Belgaum','17'),
('Bellary','17'),
('Bhatkal','17'),
('Bidar','17'),
('Bijapur','17'),
('Chamrajnagar','17'),
('Chickmagalur','17'),
('Chikballapur','17'),
('Chitradurga','17'),
('Dakshina Kannada','17'),
('Davanagere','17'),
('Dharwad','17'),
('Gadag','17'),
('Gulbarga','17'),
('Hampi','17'),
('Hassan','17'),
('Haveri','17'),
('Hospet','17'),
('Karwar','17'),
('Kodagu','17'),
('Kolar','17'),
('Koppal','17'),
('Madikeri','17'),
('Mandya','17'),
('Mangalore','17'),
('Manipal','17'),
('Mysore','17'),
('Raichur','17'),
('Shimoga','17'),
('Sirsi','17'),
('Sringeri','17'),
('Srirangapatna','17'),
('Tumkur','17'),
('Udupi','17'),
('Uttara Kannada','17');

-- Kerala
INSERT INTO Cities (name,state_id)
VALUES('Alappuzha','18'),
('Alleppey','18'),
('Alwaye','18'),
('Ernakulam','18'),
('Idukki','18'),
('Kannur','18'),
('Kasargod','18'),
('Kochi','18'),
('Kollam','18'),
('Kottayam','18'),
('Kovalam','18'),
('Kozhikode','18'),
('Malappuram','18'),
('Palakkad','18'),
('Pathanamthitta','18'),
('Perumbavoor','18'),
('Thiruvananthapuram','18'),
('Thrissur','18'),
('Trichur','18'),
('Trivandrum','18'),
('Wayanad','18');

-- Madhya Pradesh
INSERT INTO Cities (name,state_id)
VALUES('Anuppur','19'),
('Ashoknagar','19'),
('Balaghat','19'),
('Barwani','19'),
('Betul','19'),
('Bhind','19'),
('Bhopal','19'),
('Burhanpur','19'),
('Chhatarpur','19'),
('Chhindwara','19'),
('Damoh','19'),
('Datia','19'),
('Dewas','19'),
('Dhar','19'),
('Dindori','19'),
('Guna','19'),
('Gwalior','19'),
('Harda','19'),
('Hoshangabad','19'),
('Indore','19'),
('Jabalpur','19'),
('Jagdalpur','19'),
('Jhabua','19'),
('Katni','19'),
('Khandwa','19'),
('Khargone','19'),
('Mandla','19'),
('Mandsaur','19'),
('Morena','19'),
('Narsinghpur','19'),
('Neemuch','19'),
('Panna','19'),
('Raisen','19'),
('Rajgarh','19'),
('Ratlam','19'),
('Rewa','19'),
('Sagar','19'),
('Satna','19'),
('Sehore','19'),
('Seoni','19'),
('Shahdol','19'),
('Shajapur','19'),
('Sheopur','19'),
('Shivpuri','19'),
('Sidhi','19'),
('Tikamgarh','19'),
('Ujjain','19'),
('Umaria','19'),
('Vidisha','19');

-- Maharashtra
INSERT INTO Cities (name,state_id)
VALUES('Ahmednagar','20'),
('Akola','20'),
('Amravati','20'),
('Aurangabad','20'),
('Beed','20'),
('Bhandara','20'),
('Buldhana','20'),
('Chandrapur','20'),
('Dhule','20'),
('Gadchiroli','20'),
('Gondia','20'),
('Hingoli','20'),
('Jalgaon','20'),
('Jalna','20'),
('Kolhapur','20'),
('Latur','20'),
('Mahabaleshwar','20'),
('Mumbai','20'),
('Mumbai City','20'),
('Mumbai Suburban','20'),
('Nagpur','20'),
('Nanded','20'),
('Nandurbar','20'),
('Nashik','20'),
('Osmanabad','20'),
('Parbhani','20'),
('Pune','20'),
('Raigad','20'),
('Ratnagiri','20'),
('Sangli','20'),
('Satara','20'),
('Sholapur','20'),
('Sindhudurg','20'),
('Thane','20'),
('Wardha','20'),
('Washim','20'),
('Yavatmal','20');

-- Manipur
INSERT INTO Cities (name,state_id)
VALUES('Bishnupur','21'),
('Chandel','21'),
('Churachandpur','21'),
('Imphal East','21'),
('Imphal West','21'),
('Senapati','21'),
('Tamenglong','21'),
('Thoubal','21'),
('Ukhrul','21');

-- Meghalaya
INSERT INTO Cities (name,state_id)
VALUES('East Garo Hills','22'),
('East Khasi Hills','22'),
('Jaintia Hills','22'),
('Ri Bhoi','22'),
('Shillong','22'),
('South Garo Hills','22'),
('West Garo Hills','22'),
('West Khasi Hills','22');

-- Mizoram
INSERT INTO Cities (name,state_id)
VALUES('Aizawl','23'),
('Champhai','23'),
('Kolasib','23'),
('Lawngtlai','23'),
('Lunglei','23'),
('Mamit','23'),
('Saiha','23'),
('Serchhip','23');

-- Nagaland
INSERT INTO Cities (name,state_id)
VALUES('Dimapur','24'),
('Kohima','24'),
('Mokokchung','24'),
('Mon','24'),
('Phek','24'),
('Tuensang','24'),
('Wokha','24'),
('Zunheboto','24');

-- Orissa
INSERT INTO Cities (name,state_id)
VALUES('Angul','25'),
('Balangir','25'),
('Balasore','25'),
('Baleswar','25'),
('Bargarh','25'),
('Berhampur','25'),
('Bhadrak','25'),
('Bhubaneswar','25'),
('Boudh','25'),
('Cuttack','25'),
('Deogarh','25'),
('Dhenkanal','25'),
('Gajapati','25'),
('Ganjam','25'),
('Jagatsinghapur','25'),
('Jajpur','25'),
('Jharsuguda','25'),
('Kalahandi','25'),
('Kandhamal','25'),
('Kendrapara','25'),
('Kendujhar','25'),
('Khordha','25'),
('Koraput','25'),
('Malkangiri','25'),
('Mayurbhanj','25'),
('Nabarangapur','25'),
('Nayagarh','25'),
('Nuapada','25'),
('Puri','25'),
('Rayagada','25'),
('Rourkela','25'),
('Sambalpur','25'),
('Subarnapur','25'),
('Sundergarh','25');

-- Pondicherry
INSERT INTO Cities (name,state_id)
VALUES('Bahur','26'),
('Karaikal','26'),
('Mahe','26'),
('Pondicherry','26'),
('Purnankuppam','26'),
('Valudavur','26'),
('Villianur','26'),
('Yanam','26');

-- Punjab
INSERT INTO Cities (name,state_id)
VALUES('Amritsar','27'),
('Barnala','27'),
('Bathinda','27'),
('Faridkot','27'),
('Fatehgarh Sahib','27'),
('Ferozepur','27'),
('Gurdaspur','27'),
('Hoshiarpur','27'),
('Jalandhar','27'),
('Kapurthala','27'),
('Ludhiana','27'),
('Mansa','27'),
('Moga','27'),
('Muktsar','27'),
('Nawanshahr','27'),
('Pathankot','27'),
('Patiala','27'),
('Rupnagar','27'),
('Sangrur','27'),
('SAS Nagar','27'),
('Tarn Taran','27');

-- Rajasthan
INSERT INTO Cities (name,state_id)
VALUES('Ajmer','28'),
('Alwar','28'),
('Banswara','28'),
('Baran','28'),
('Barmer','28'),
('Bharatpur','28'),
('Bhilwara','28'),
('Bikaner','28'),
('Bundi','28'),
('Chittorgarh','28'),
('Churu','28'),
('Dausa','28'),
('Dholpur','28'),
('Dungarpur','28'),
('Hanumangarh','28'),
('Jaipur','28'),
('Jaisalmer','28'),
('Jalore','28'),
('Jhalawar','28'),
('Jhunjhunu','28'),
('Jodhpur','28'),
('Karauli','28'),
('Kota','28'),
('Nagaur','28'),
('Pali','28'),
('Pilani','28'),
('Rajsamand','28'),
('Sawai Madhopur','28'),
('Sikar','28'),
('Sirohi','28'),
('Sri Ganganagar','28'),
('Tonk','28'),
('Udaipur','28');

-- Sikkim
INSERT INTO Cities (name,state_id)
VALUES('Barmiak','29'),
('Be','29'),
('Bhurtuk','29'),
('Chhubakha','29'),
('Chidam','29'),
('Chubha','29'),
('Chumikteng','29'),
('Dentam','29'),
('Dikchu','29'),
('Dzongri','29'),
('Gangtok','29'),
('Gauzing','29'),
('Gyalshing','29'),
('Hema','29'),
('Kerung','29'),
('Lachen','29'),
('Lachung','29'),
('Lema','29'),
('Lingtam','29'),
('Lungthu','29'),
('Mangan','29'),
('Namchi','29'),
('Namthang','29'),
('Nanga','29'),
('Nantang','29'),
('Naya Bazar','29'),
('Padamachen','29'),
('Pakhyong','29'),
('Pemayangtse','29'),
('Phensang','29'),
('Rangli','29'),
('Rinchingpong','29'),
('Sakyong','29'),
('Samdong','29'),
('Singtam','29'),
('Siniolchu','29'),
('Sombari','29'),
('Soreng','29'),
('Sosing','29'),
('Tekhug','29'),
('Temi','29'),
('Tsetang','29'),
('Tsomgo','29'),
('Tumlong','29'),
('Yangang','29'),
('Yumtang','29');

-- Tamil Nadu
INSERT INTO Cities (name,state_id)
VALUES('Chennai','30'),
('Chidambaram','30'),
('Chingleput','30'),
('Coimbatore','30'),
('Courtallam','30'),
('Cuddalore','30'),
('Dharmapuri','30'),
('Dindigul','30'),
('Erode','30'),
('Hosur','30'),
('Kanchipuram','30'),
('Kanyakumari','30'),
('Karaikudi','30'),
('Karur','30'),
('Kodaikanal','30'),
('Kovilpatti','30'),
('Krishnagiri','30'),
('Kumbakonam','30'),
('Madurai','30'),
('Mayiladuthurai','30'),
('Nagapattinam','30'),
('Nagarcoil','30'),
('Namakkal','30'),
('Neyveli','30'),
('Nilgiris','30'),
('Ooty','30'),
('Palani','30'),
('Perambalur','30'),
('Pollachi','30'),
('Pudukkottai','30'),
('Rajapalayam','30'),
('Ramanathapuram','30'),
('Salem','30'),
('Sivaganga','30'),
('Sivakasi','30'),
('Thanjavur','30'),
('Theni','30'),
('Thoothukudi','30'),
('Tiruchirappalli','30'),
('Tirunelveli','30'),
('Tirupur','30'),
('Tiruvallur','30'),
('Tiruvannamalai','30'),
('Tiruvarur','30'),
('Trichy','30'),
('Tuticorin','30'),
('Vellore','30'),
('Villupuram','30'),
('Virudhunagar','30'),
('Yercaud','30');

-- Tripura
INSERT INTO Cities (name,state_id)
VALUES('Agartala','31'),
('Ambasa','31'),
('Bampurbari','31'),
('Belonia','31'),
('Dhalai','31'),
('Dharam Nagar','31'),
('Kailashahar','31'),
('Kamal Krishnabari','31'),
('Khopaiyapara','31'),
('Khowai','31'),
('Phuldungsei','31'),
('Radha Kishore Pur','31'),
('Tripura','31');
