\c next-handy-gst
CREATE SCHEMA IF NOT EXISTS :v1 AUTHORIZATION postgres;
SET search_path = :v1;
\i renderer/prisma/migrations/init/migration.sql;

--Add default user
INSERT INTO "User"(username, first_name, last_name,phone, email, code, type, password, updated_at)VALUES ('admin','admin','admin','1234567890','admin@admin.com','25','administrator','$2a$12$8DhyGUPa1YYWMxVeyGN/6e2uB2iYRJlaWsKpqSurfXfw5xck2NQRy',now());

--Add All states
INSERT INTO "State"(gst_code, name, priority, abbreviation, updated_at) VALUES ('35', 'Andaman & Nicobar','1','AN', now()),('37', 'Andhra Pradesh','1','AP', now()),('12', 'Arunachal Pradesh','1','AR', now()),('18', 'Assam','1','AS', now()),('10', 'Bihar','1','BH', now()),('4', 'Chandigarh','1','CH', now()),('22', 'Chhattisgarh','1','CG', now()),('26', 'Dadra & Nagar Haveli','1','DN', now()),('26', 'Daman & Diu','1','DD', now()),('7', 'Delhi','1','DL', now()),('30', 'Goa','1','GO', now()),('24', 'Gujarat','1','GU', now()),('6', 'Haryana','1','HR', now()),('2', 'Himachal Pradesh','1','HP', now()),('1', 'Jammu & Kashmir','1','JK', now()),('20', 'Jharkhand','1','JH', now()),('29', 'Karnataka','1','KR', now()),('32', 'Kerala','1','KL', now()),('23', 'Madhya Pradesh','1','MP', now()),('27', 'Maharashtra','1','MH', now()),('14', 'Manipur','1','MN', now()),('17', 'Meghalaya','1','ML', now()),('25', 'Mizoram','1','MM', now()),('13', 'Nagaland','1','NL', now()),('21', 'Orissa','1','OR', now()),('34', 'Pondicherry','1','PC', now()),('3', 'Punjab','1','PJ', now()),('8', 'Rajasthan','1','RJ', now()),('11', 'Sikkim','1','SK', now()),('33', 'Tamil Nadu','1','TN', now()),('16', 'Tripura','1','TR', now()),('9', 'Uttar Pradesh','1','UP', now()),('5', 'UTTARAKHAND','1','UK', now()),('19', 'West Bengal','1','WB', now());

-- Andaman & Nicobar
INSERT INTO "City"(name, state_id, updated_at) VALUES('Alipur', '1', now()),('Andaman Island', '1', now()),('Anderson Island', '1', now()),('Arainj-Laka-Punga', '1', now()),('Austinabad', '1', now()),('Bamboo Flat', '1', now()),('Barren Island', '1', now()),('Beadonabad', '1', now()),('Betapur', '1', now()),('Bindraban', '1', now()),('Bonington', '1', now()),('Brookesabad', '1', now()),('Cadell Point', '1', now()),('Calicut', '1', now()),('Chetamale', '1', now()),('Cinque Islands', '1', now()),('Defence Island', '1', now()),('Digilpur', '1', now()),('Dolyganj', '1', now()),('Flat Island', '1', now()),('Geinyale', '1', now()),('Great Coco Island', '1', now()),('Haddo', '1', now()),('Havelock Island', '1', now()),('Henry Lawrence Island', '1', now()),('Herbertabad', '1', now()),('Hobdaypur', '1', now()),('Ilichar', '1', now()),('Ingoie', '1', now()),('Inteview Island', '1', now()),('Jangli Ghat', '1', now()),('Jhon Lawrence Island', '1', now()),('Karen', '1', now()),('Kartara', '1', now()),('KYD Islannd', '1', now()),('Landfall Island', '1', now()),('Little Andmand', '1', now()),('Little Coco Island', '1', now()),('Long Island', '1', now()),('Maimyo', '1', now()),('Malappuram', '1', now()),('Manglutan', '1', now()),('Manpur', '1', now()),('Mitha Khari', '1', now()),('Neill Island', '1', now()),('Nicobar Island', '1', now()),('North Brother Island', '1', now()),('North Passage Island', '1', now()),('North Sentinel Island', '1', now()),('Nothen Reef Island', '1', now()),('Outram Island', '1', now()),('Pahlagaon', '1', now()),('Palalankwe', '1', now()),('Passage Island', '1', now()),('Phaiapong', '1', now()),('Phoenix Island', '1', now()),('Port Blair', '1', now()),('Preparis Island', '1', now()),('Protheroepur', '1', now()),('Rangachang', '1', now()),('Rongat', '1', now()),('Rutland Island', '1', now()),('Sabari', '1', now()),('Saddle Peak', '1', now()),('Shadipur', '1', now()),('Smith Island', '1', now()),('Sound Island', '1', now()),('South Sentinel Island', '1', now()),('Spike Island', '1', now()),('Tarmugli Island', '1', now()),('Taylerabad', '1', now()),('Titaije', '1', now()),('Toibalawe', '1', now()),('Tusonabad', '1', now()),('West Island', '1', now()),('Wimberleyganj', '1', now()),('Yadita', '1', now());

-- Andhra Pradesh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Adilabad', '2', now()),('Anantapur', '2', now()),('Chittoor', '2', now()),('Cuddapah', '2', now()),('East Godavari', '2', now()),('Guntur', '2', now()),('Hyderabad', '2', now()),('Karimnagar', '2', now()),('Khammam', '2', now()),('Krishna', '2', now()),('Kurnool', '2', now()),('Mahabubnagar', '2', now()),('Medak', '2', now()),('Nalgonda', '2', now()),('Nellore', '2', now()),('Nizamabad', '2', now()),('Prakasam', '2', now()),('Rangareddy', '2', now()),('Srikakulam', '2', now()),('Visakhapatnam', '2', now()),('Vizianagaram', '2', now()),('Warangal', '2', now()),('West Godavari', '2', now());

-- Arunachal Pradesh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Anjaw', '3', now()),('Changlang', '3', now()),('Dibang Valley', '3', now()),('East Kameng', '3', now()),('East Siang', '3', now()),('Itanagar', '3', now()),('Kurung Kumey', '3', now()),('Lohit', '3', now()),('Lower Dibang Valley', '3', now()),('Lower Subansiri', '3', now()),('Papum Pare', '3', now()),('Tawang', '3', now()),('Tirap', '3', now()),('Upper Siang', '3', now()),('Upper Subansiri', '3', now()),('West Kameng', '3', now()),('West Siang', '3', now());

-- Assam
INSERT INTO "City"(name, state_id, updated_at) VALUES('Barpeta', '4', now()),('Bongaigaon', '4', now()),('Cachar', '4', now()),('Darrang', '4', now()),('Dhemaji', '4', now()),('Dhubri', '4', now()),('Dibrugarh', '4', now()),('Goalpara', '4', now()),('Golaghat', '4', now()),('Guwahati', '4', now()),('Hailakandi', '4', now()),('Jorhat', '4', now()),('Kamrup', '4', now()),('Karbi Anglong', '4', now()),('Karimganj', '4', now()),('Kokrajhar', '4', now()),('Lakhimpur', '4', now()),('Marigaon', '4', now()),('Nagaon', '4', now()),('Nalbari', '4', now()),('North Cachar Hills', '4', now()),('Silchar', '4', now()),('Sivasagar', '4', now()),('Sonitpur', '4', now()),('Tinsukia', '4', now()),('Udalguri', '4', now());

-- Bihar
INSERT INTO "City"(name, state_id, updated_at) VALUES('Araria', '5', now()),('Aurangabad', '5', now()),('Banka', '5', now()),('Begusarai', '5', now()),('Bhagalpur', '5', now()),('Bhojpur', '5', now()),('Buxar', '5', now()),('Darbhanga', '5', now()),('East Champaran', '5', now()),('Gaya', '5', now()),('Gopalganj', '5', now()),('Jamshedpur', '5', now()),('Jamui', '5', now()),('Jehanabad', '5', now()),('Kaimur (Bhabua)', '5', now()),('Katihar', '5', now()),('Khagaria', '5', now()),('Kishanganj', '5', now()),('Lakhisarai', '5', now()),('Madhepura', '5', now()),('Madhubani', '5', now()),('Munger', '5', now()),('Muzaffarpur', '5', now()),('Nalanda', '5', now()),('Nawada', '5', now()),('Patna', '5', now()),('Purnia', '5', now()),('Rohtas', '5', now()),('Saharsa', '5', now()),('Samastipur', '5', now()),('Saran', '5', now()),('Sheikhpura', '5', now()),('Sheohar', '5', now()),('Sitamarhi', '5', now()),('Siwan', '5', now()),('Supaul', '5', now()),('Vaishali', '5', now()),('West Champaran', '5', now());

-- Chandigarh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Chandigarh', '6', now()),('Mani Marja', '6', now());

-- Chhattisgarh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bastar', '7', now()),('Bhilai', '7', now()),('Bijapur', '7', now()),('Bilaspur', '7', now()),('Dhamtari', '7', now()),('Durg', '7', now()),('Janjgir-Champa', '7', now()),('Jashpur', '7', now()),('Kabirdham-Kawardha', '7', now()),('Korba', '7', now()),('Korea', '7', now()),('Mahasamund', '7', now()),('Narayanpur', '7', now()),('Norh Bastar-Kanker', '7', now()),('Raigarh', '7', now()),('Raipur', '7', now()),('Rajnandgaon', '7', now()),('South Bastar-Dantewada', '7', now()),('Surguja', '7', now());

-- Dadra & Nagar Haveli
INSERT INTO "City"(name, state_id, updated_at) VALUES('Amal', '8', now()),('Amli', '8', now()),('Bedpa', '8', now()),('Chikhli', '8', now()),('Dadra & Nagar Haveli', '8', now()),('Dahikhed', '8', now()),('Dolara', '8', now()),('Galonda', '8', now()),('Kanadi', '8', now()),('Karchond', '8', now()),('Khadoli', '8', now()),('Kharadpada', '8', now()),('Kherabari', '8', now()),('Kherdi', '8', now()),('Kothar', '8', now()),('Luari', '8', now()),('Mashat', '8', now()),('Rakholi', '8', now()),('Rudana', '8', now()),('Saili', '8', now()),('Sili', '8', now()),('Silvassa', '8', now()),('Sindavni', '8', now()),('Udva', '8', now()),('Umbarkoi', '8', now()),('Vansda', '8', now()),('Vasona', '8', now()),('Velugam', '8', now());

-- Daman and Diu
INSERT INTO "City"(name, state_id, updated_at) VALUES('Brancavare', '9', now()),('Dagasi', '9', now()),('Daman', '9', now()),('Diu', '9', now()),('Magarvara', '9', now()),('Nagwa', '9', now()),('Pariali', '9', now()),('Passo Covo', '9', now());

-- Delhi
INSERT INTO "City"(name, state_id, updated_at) VALUES('Central Delhi','10', now()),('East Delhi','10', now()),('New Delhi','10', now()),('North Delhi','10', now()),('North East Delhi','10', now()),('North West Delhi','10', now()),('Old Delhi','10', now()),('South Delhi','10', now()),('South West Delhi','10', now()),('West Delhi','10', now());

--  Goa
INSERT INTO "City"(name, state_id, updated_at) VALUES('Canacona','11', now()),('Candolim','11', now()),('Chinchinim','11', now()),('Cortalim','11', now()),('Goa','11', now()),('Jua','11', now()),('Madgaon','11', now()),('Mahem','11', now()),('Mapuca','11', now()),('Marmagao','11', now()),('Panji','11', now()),('Ponda','11', now()),('Sanvordem','11', now()),('Terekhol','11', now());

-- Gujarat
INSERT INTO "City"(name, state_id, updated_at) VALUES('Ahmedabad','12', now()),('Amreli','12', now()),('Anand','12', now()),('Banaskantha','12', now()),('Baroda','12', now()),('Bharuch','12', now()),('Bhavnagar','12', now()),('Dahod','12', now()),('Dang','12', now()),('Dwarka','12', now()),('Gandhinagar','12', now()),('Jamnagar','12', now()),('Junagadh','12', now()),('Kheda','12', now()),('Kutch','12', now()),('Mehsana','12', now()),('Nadiad','12', now()),('Narmada','12', now()),('Navsari','12', now()),('Panchmahals','12', now()),('Patan','12', now()),('Porbandar','12', now()),('Rajkot','12', now()),('Sabarkantha','12', now()),('Surat','12', now()),('Surendranagar','12', now()),('Vadodara','12', now()),('Valsad','12', now()),('Vapi','12', now());

-- Haryana
INSERT INTO "City"(name, state_id, updated_at) VALUES('Ambala','13', now()),('Bhiwani','13', now()),('Faridabad','13', now()),('Fatehabad','13', now()),('Gurgaon','13', now()),('Hisar','13', now()),('Jhajjar','13', now()),('Jind','13', now()),('Kaithal','13', now()),('Karnal','13', now()),('Kurukshetra','13', now()),('Mahendragarh','13', now()),('Mewat','13', now()),('Panchkula','13', now()),('Panipat','13', now()),('Rewari','13', now()),('Rohtak','13', now()),('Sirsa','13', now()),('Sonipat','13', now()),('Yamunanagar','13', now());

-- Himachal Pradesh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bilaspur','14', now()),('Chamba','14', now()),('Dalhousie','14', now()),('Hamirpur','14', now()),('Kangra','14', now()),('Kinnaur','14', now()),('Kullu','14', now()),('Lahaul & Spiti','14', now()),('Mandi','14', now()),('Shimla','14', now()),('Sirmaur','14', now()),('Solan','14', now()),('Una','14', now());

-- Jammu & Kashmir
INSERT INTO "City"(name, state_id, updated_at) VALUES('Anantnag','15', now()),('Baramulla','15', now()),('Budgam','15', now()),('Doda','15', now()),('Jammu','15', now()),('Kargil','15', now()),('Kathua','15', now()),('Kupwara','15', now()),('Leh','15', now()),('Poonch','15', now()),('Pulwama','15', now()),('Rajauri','15', now()),('Srinagar','15', now()),('Udhampur','15', now());

-- Jharkhand
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bokaro','16', now()),('Chatra','16', now()),('Deoghar','16', now()),('Dhanbad','16', now()),('Dumka','16', now()),('East Singhbhum','16', now()),('Garhwa','16', now()),('Giridih','16', now()),('Godda','16', now()),('Gumla','16', now()),('Hazaribag','16', now()),('Jamtara','16', now()),('Koderma','16', now()),('Latehar','16', now()),('Lohardaga','16', now()),('Pakur','16', now()),('Palamu','16', now()),('Ranchi','16', now()),('Sahibganj','16', now()),('Seraikela','16', now()),('Simdega','16', now()),('West Singhbhum','16', now());

-- Karnataka
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bagalkot','17', now()),('Bangalore','17', now()),('Bangalore Rural','17', now()),('Belgaum','17', now()),('Bellary','17', now()),('Bhatkal','17', now()),('Bidar','17', now()),('Bijapur','17', now()),('Chamrajnagar','17', now()),('Chickmagalur','17', now()),('Chikballapur','17', now()),('Chitradurga','17', now()),('Dakshina Kannada','17', now()),('Davanagere','17', now()),('Dharwad','17', now()),('Gadag','17', now()),('Gulbarga','17', now()),('Hampi','17', now()),('Hassan','17', now()),('Haveri','17', now()),('Hospet','17', now()),('Karwar','17', now()),('Kodagu','17', now()),('Kolar','17', now()),('Koppal','17', now()),('Madikeri','17', now()),('Mandya','17', now()),('Mangalore','17', now()),('Manipal','17', now()),('Mysore','17', now()),('Raichur','17', now()),('Shimoga','17', now()),('Sirsi','17', now()),('Sringeri','17', now()),('Srirangapatna','17', now()),('Tumkur','17', now()),('Udupi','17', now()),('Uttara Kannada','17', now());

-- Kerala
INSERT INTO "City"(name, state_id, updated_at) VALUES('Alappuzha','18', now()),('Alleppey','18', now()),('Alwaye','18', now()),('Ernakulam','18', now()),('Idukki','18', now()),('Kannur','18', now()),('Kasargod','18', now()),('Kochi','18', now()),('Kollam','18', now()),('Kottayam','18', now()),('Kovalam','18', now()),('Kozhikode','18', now()),('Malappuram','18', now()),('Palakkad','18', now()),('Pathanamthitta','18', now()),('Perumbavoor','18', now()),('Thiruvananthapuram','18', now()),('Thrissur','18', now()),('Trichur','18', now()),('Trivandrum','18', now()),('Wayanad','18', now());

-- Madhya Pradesh
INSERT INTO "City"(name, state_id, updated_at) VALUES('Anuppur','19', now()),('Ashoknagar','19', now()),('Balaghat','19', now()),('Barwani','19', now()),('Betul','19', now()),('Bhind','19', now()),('Bhopal','19', now()),('Burhanpur','19', now()),('Chhatarpur','19', now()),('Chhindwara','19', now()),('Damoh','19', now()),('Datia','19', now()),('Dewas','19', now()),('Dhar','19', now()),('Dindori','19', now()),('Guna','19', now()),('Gwalior','19', now()),('Harda','19', now()),('Hoshangabad','19', now()),('Indore','19', now()),('Jabalpur','19', now()),('Jagdalpur','19', now()),('Jhabua','19', now()),('Katni','19', now()),('Khandwa','19', now()),('Khargone','19', now()),('Mandla','19', now()),('Mandsaur','19', now()),('Morena','19', now()),('Narsinghpur','19', now()),('Neemuch','19', now()),('Panna','19', now()),('Raisen','19', now()),('Rajgarh','19', now()),('Ratlam','19', now()),('Rewa','19', now()),('Sagar','19', now()),('Satna','19', now()),('Sehore','19', now()),('Seoni','19', now()),('Shahdol','19', now()),('Shajapur','19', now()),('Sheopur','19', now()),('Shivpuri','19', now()),('Sidhi','19', now()),('Tikamgarh','19', now()),('Ujjain','19', now()),('Umaria','19', now()),('Vidisha','19', now());

-- Maharashtra
INSERT INTO "City"(name, state_id, updated_at) VALUES('Ahmednagar','20', now()),('Akola','20', now()),('Amravati','20', now()),('Aurangabad','20', now()),('Beed','20', now()),('Bhandara','20', now()),('Buldhana','20', now()),('Chandrapur','20', now()),('Dhule','20', now()),('Gadchiroli','20', now()),('Gondia','20', now()),('Hingoli','20', now()),('Jalgaon','20', now()),('Jalna','20', now()),('Kolhapur','20', now()),('Latur','20', now()),('Mahabaleshwar','20', now()),('Mumbai','20', now()),('Mumbai City','20', now()),('Mumbai Suburban','20', now()),('Nagpur','20', now()),('Nanded','20', now()),('Nandurbar','20', now()),('Nashik','20', now()),('Osmanabad','20', now()),('Parbhani','20', now()),('Pune','20', now()),('Raigad','20', now()),('Ratnagiri','20', now()),('Sangli','20', now()),('Satara','20', now()),('Sholapur','20', now()),('Sindhudurg','20', now()),('Thane','20', now()),('Wardha','20', now()),('Washim','20', now()),('Yavatmal','20', now());

-- Manipur
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bishnupur','21', now()),('Chandel','21', now()),('Churachandpur','21', now()),('Imphal East','21', now()),('Imphal West','21', now()),('Senapati','21', now()),('Tamenglong','21', now()),('Thoubal','21', now()),('Ukhrul','21', now());

-- Meghalaya
INSERT INTO "City"(name, state_id, updated_at) VALUES('East Garo Hills','22', now()),('East Khasi Hills','22', now()),('Jaintia Hills','22', now()),('Ri Bhoi','22', now()),('Shillong','22', now()),('South Garo Hills','22', now()),('West Garo Hills','22', now()),('West Khasi Hills','22', now());

-- Mizoram
INSERT INTO "City"(name, state_id, updated_at) VALUES('Aizawl','23', now()),('Champhai','23', now()),('Kolasib','23', now()),('Lawngtlai','23', now()),('Lunglei','23', now()),('Mamit','23', now()),('Saiha','23', now()),('Serchhip','23', now());

-- Nagaland
INSERT INTO "City"(name, state_id, updated_at) VALUES('Dimapur','24', now()),('Kohima','24', now()),('Mokokchung','24', now()),('Mon','24', now()),('Phek','24', now()),('Tuensang','24', now()),('Wokha','24', now()),('Zunheboto','24', now());

-- Orissa
INSERT INTO "City"(name, state_id, updated_at) VALUES('Angul','25', now()),('Balangir','25', now()),('Balasore','25', now()),('Baleswar','25', now()),('Bargarh','25', now()),('Berhampur','25', now()),('Bhadrak','25', now()),('Bhubaneswar','25', now()),('Boudh','25', now()),('Cuttack','25', now()),('Deogarh','25', now()),('Dhenkanal','25', now()),('Gajapati','25', now()),('Ganjam','25', now()),('Jagatsinghapur','25', now()),('Jajpur','25', now()),('Jharsuguda','25', now()),('Kalahandi','25', now()),('Kandhamal','25', now()),('Kendrapara','25', now()),('Kendujhar','25', now()),('Khordha','25', now()),('Koraput','25', now()),('Malkangiri','25', now()),('Mayurbhanj','25', now()),('Nabarangapur','25', now()),('Nayagarh','25', now()),('Nuapada','25', now()),('Puri','25', now()),('Rayagada','25', now()),('Rourkela','25', now()),('Sambalpur','25', now()),('Subarnapur','25', now()),('Sundergarh','25', now());

-- Pondicherry
INSERT INTO "City"(name, state_id, updated_at) VALUES('Bahur','26', now()),('Karaikal','26', now()),('Mahe','26', now()),('Pondicherry','26', now()),('Purnankuppam','26', now()),('Valudavur','26', now()),('Villianur','26', now()),('Yanam','26', now());

-- Punjab
INSERT INTO "City"(name, state_id, updated_at) VALUES('Amritsar','27', now()),('Barnala','27', now()),('Bathinda','27', now()),('Faridkot','27', now()),('Fatehgarh Sahib','27', now()),('Ferozepur','27', now()),('Gurdaspur','27', now()),('Hoshiarpur','27', now()),('Jalandhar','27', now()),('Kapurthala','27', now()),('Ludhiana','27', now()),('Mansa','27', now()),('Moga','27', now()),('Muktsar','27', now()),('Nawanshahr','27', now()),('Pathankot','27', now()),('Patiala','27', now()),('Rupnagar','27', now()),('Sangrur','27', now()),('SAS Nagar','27', now()),('Tarn Taran','27', now());

-- Rajasthan
INSERT INTO "City"(name, state_id, updated_at) VALUES('Ajmer','28', now()),('Alwar','28', now()),('Banswara','28', now()),('Baran','28', now()),('Barmer','28', now()),('Bharatpur','28', now()),('Bhilwara','28', now()),('Bikaner','28', now()),('Bundi','28', now()),('Chittorgarh','28', now()),('Churu','28', now()),('Dausa','28', now()),('Dholpur','28', now()),('Dungarpur','28', now()),('Hanumangarh','28', now()),('Jaipur','28', now()),('Jaisalmer','28', now()),('Jalore','28', now()),('Jhalawar','28', now()),('Jhunjhunu','28', now()),('Jodhpur','28', now()),('Karauli','28', now()),('Kota','28', now()),('Nagaur','28', now()),('Pali','28', now()),('Pilani','28', now()),('Rajsamand','28', now()),('Sawai Madhopur','28', now()),('Sikar','28', now()),('Sirohi','28', now()),('Sri Ganganagar','28', now()),('Tonk','28', now()),('Udaipur','28', now());

-- Sikkim
INSERT INTO "City"(name, state_id, updated_at) VALUES('Barmiak','29', now()),('Be','29', now()),('Bhurtuk','29', now()),('Chhubakha','29', now()),('Chidam','29', now()),('Chubha','29', now()),('Chumikteng','29', now()),('Dentam','29', now()),('Dikchu','29', now()),('Dzongri','29', now()),('Gangtok','29', now()),('Gauzing','29', now()),('Gyalshing','29', now()),('Hema','29', now()),('Kerung','29', now()),('Lachen','29', now()),('Lachung','29', now()),('Lema','29', now()),('Lingtam','29', now()),('Lungthu','29', now()),('Mangan','29', now()),('Namchi','29', now()),('Namthang','29', now()),('Nanga','29', now()),('Nantang','29', now()),('Naya Bazar','29', now()),('Padamachen','29', now()),('Pakhyong','29', now()),('Pemayangtse','29', now()),('Phensang','29', now()),('Rangli','29', now()),('Rinchingpong','29', now()),('Sakyong','29', now()),('Samdong','29', now()),('Singtam','29', now()),('Siniolchu','29', now()),('Sombari','29', now()),('Soreng','29', now()),('Sosing','29', now()),('Tekhug','29', now()),('Temi','29', now()),('Tsetang','29', now()),('Tsomgo','29', now()),('Tumlong','29', now()),('Yangang','29', now()),('Yumtang','29', now());

-- Tamil Nadu
INSERT INTO "City"(name, state_id, updated_at) VALUES('Chennai','30', now()),('Chidambaram','30', now()),('Chingleput','30', now()),('Coimbatore','30', now()),('Courtallam','30', now()),('Cuddalore','30', now()),('Dharmapuri','30', now()),('Dindigul','30', now()),('Erode','30', now()),('Hosur','30', now()),('Kanchipuram','30', now()),('Kanyakumari','30', now()),('Karaikudi','30', now()),('Karur','30', now()),('Kodaikanal','30', now()),('Kovilpatti','30', now()),('Krishnagiri','30', now()),('Kumbakonam','30', now()),('Madurai','30', now()),('Mayiladuthurai','30', now()),('Nagapattinam','30', now()),('Nagarcoil','30', now()),('Namakkal','30', now()),('Neyveli','30', now()),('Nilgiris','30', now()),('Ooty','30', now()),('Palani','30', now()),('Perambalur','30', now()),('Pollachi','30', now()),('Pudukkottai','30', now()),('Rajapalayam','30', now()),('Ramanathapuram','30', now()),('Salem','30', now()),('Sivaganga','30', now()),('Sivakasi','30', now()),('Thanjavur','30', now()),('Theni','30', now()),('Thoothukudi','30', now()),('Tiruchirappalli','30', now()),('Tirunelveli','30', now()),('Tirupur','30', now()),('Tiruvallur','30', now()),('Tiruvannamalai','30', now()),('Tiruvarur','30', now()),('Trichy','30', now()),('Tuticorin','30', now()),('Vellore','30', now()),('Villupuram','30', now()),('Virudhunagar','30', now()),('Yercaud','30', now());

-- Tripura
INSERT INTO "City"(name, state_id, updated_at) VALUES('Agartala','31', now()),('Ambasa','31', now()),('Bampurbari','31', now()),('Belonia','31', now()),('Dhalai','31', now()),('Dharam Nagar','31', now()),('Kailashahar','31', now()),('Kamal Krishnabari','31', now()),('Khopaiyapara','31', now()),('Khowai','31', now()),('Phuldungsei','31', now()),('Radha Kishore Pur','31', now()),('Tripura','31', now());
